### ISSUE TITLE
Error message on upload "Operation not permitted"

### ISSUE THREAD

**Issue by rasteiner** [k-next/kirby#5024]
## Description
In some environments, after uploading files through the panel the following error message is shown:

```
myfilename.jpg

rename(/tmp/63d1538df3338.20221110myfilename.jpg,/home/path/to/web/root/content/home/myfilename.jpg) [<a href='https://secure.php.net/manual/en/function.rename.php'>function.rename.php</a>]: Operation not permitted
```
The file is however correctly uploaded, implying the fact that this is not a permissions issue. The error message and `400` status of the request also prevent a `files` field to automatically select the *just uploaded* file. 

**Expected behavior**  
No error message should be shown if the upload has succeeded. 

**Screenshots**  
<img width="361" alt="image" src="https://user-images.githubusercontent.com/6684137/214623609-981c75bc-e463-47b2-82fa-403b4264cdc5.png">

## To reproduce

This issue is only visible in certain environments. See *Additional Context*

1. Login to the panel
2. Upload or replace a file

## Your setup
**Kirby Version**  
Kirby 3.9.0

**Console output**  
no stack trace is included, even with `'debug' => true`

**Server system**
FreeBSD 12.4-RELEASE releng/12.4-n235809-f2877ac4fb03 HOSTPOINT  amd64

**Additional context**  
Searching the internets, this corresponds:
https://stackoverflow.com/questions/45692433/php-rename-from-tmp-throws-warning-although-actually-works
The answer there mentions that `rename` throws a warning when moving files across file systems. It suggests using `copy` + `unlink` instead.
Since 3.9.0-rc-2 introduced ["Support moving source files on create and replace"](https://github.com/getkirby/kirby/commit/14f2e69bd68f8970fa504f7ac841d02b42503601) this might be something. Before 3.9 files were simply copied. 
This also explains why the error only shows up in certain environments (`/tmp` and `/content` must be on different file systems / mounts).

**Comment by rasteiner** [comment]
Patching https://github.com/getkirby/kirby/blob/760a02f95773787cdd03e6bf963a8b1c2ff1db3d/src/Filesystem/F.php#L524-L527 to the following resolves the issue:

```php
	// actually move the file
	if (copy($oldRoot, $newRoot) !== true || unlink($oldRoot) !== true) {
		return false;
	}
```

So does:
```php
	// actually move the file
	if (@rename($oldRoot, $newRoot) !== true) {
		return false;
	}
```

Swallowing the error / warning might actually be the better approach considering we still check for failure with the if statement.

**Comment by lukasbestle** [comment]
Thanks for your research!

I'm not sure about swallowing the warning though. It would make it super hard to debug other unrelated issues later.

To make the operation atomic, I think the logic should work like this:

- First copy the file.
- Then check if the copy was successful (= if `copy()` returned `true`).
  - If the copy operation failed, `unlink()` the `$newRoot` and return `false`.
  - If the copy operation was successful, `unlink()` the `$oldRoot`.

**Comment by rasteiner** [comment]
Sure, my thought was just that copy+unlink loses the advantage of the rename being instantaneous even for large files (at least when moving on the same filesystem)

**Comment by lukasbestle** [comment]
That is true...

**Comment by rasteiner** [comment]
Otherwise something like this seems to work in my environments:

```php 
	// actually move the file
	$error = null;
	set_error_handler(fn($no, $str, $file, $line) => $error = $str);
	$callResult = rename($oldRoot, $newRoot);
	restore_error_handler();

	if ($callResult !== true) {
		throw new \Exception($error);
	}
```

this "catches" an eventual error or warning and throws it as exception, but only if the call actually fails (i.e. returns `false`).

--- 

I guess that would however be technically a breaking change, it no longer just returns `false` on failure but actually throws an exception. The difference between "I'll just print an error to stderr" and "throw an exception" being that unhandled exceptions halt the execution, while errors just ruin the output... 🤷

**Comment by lukasbestle** [comment]
Yeah. I think if we could set up the Toolkit from scratch, we would use exceptions throughout and get rid of the boolean return values. I guess the PHP team would do the same if they could set up the PHP core from scratch. ;)

I wonder if the performance hit for copying and removing the original file would be that bad. Many file systems use copy-on-write logic nowadays, there it won't matter at all because the file contents are not actually copied when the pointer is copied. So I guess this becomes a trade-off question (between reliability and performance) and a question of file system market shares.

**Comment by rasteiner** [comment]
Another option could be to introduce a new method or a new mode to `F::move`, one that explicitly does "copy & unlink" so that a "pure" `move` function stays in the toolkit. This way the upload function could use `copy&unlink` while the "rename folders out of `_draft`" functionality keeps using the pure `move`. 

I guess it's pretty common for shared hosting plans to mount the user code from a separate machine into webservers that have their own `/tmp` directory. While it would be uncommon for different parts of, for example, the `content` folder to be on separate partitions... 
So "moving uploaded files" is actually a kind of special use case that might deserve its own function, because it's often times from a folder that is outside of the site installation. 
Also, uploaded files statistically probably aren't huge files, while who knows what people use the Toolkit for 😅

**Comment by lukasbestle** [comment]
Maybe the new method could be called `F::atomicMove()`.

**Comment by rasteiner** [comment]
I personally would be a bit confused about having the variant with `rename` be called just `move` and the new method with copy & unlink being called `atomicMove`. 
To me the word "atomic" promises something to be thread safe. In the context of moving files that would mean that the file, in any given instant, is either in the new place in its entirety, or not there at all. 
Copy & unlink does not guarantee that, while rename (normally) does. That's not really a problem per se, if there's no alternative to a copy, but for me it's really the opposite of what "atomic" means. 

If you want to make it the most atomic possible, I guess you could first copy the file to a temporary path inside the site installation and then rename it to the definitive path. But I don't know how much this is worth it... 

--- 

what about an explicit "F::moveByCopy()"? Too verbose?

**Comment by lukasbestle** [comment]
You are right, I got that logic reversed in my head. `moveByCopy()` sounds great IMO.

**Comment by iskrisis** [comment]
Started to happen on my mac dev machine not sure why. The file gets uploaded even through the error message. I get error message even with @rasteiner solutions just different one " The file could not be uploaded ". But what it fixes are file hooks. When i get the `rename not permitted` file gets uploaded but no file hooks fire.

**Comment by lukasbestle** [comment]
@iskrisis That will be a different issue then. Could you replace [this line](https://github.com/getkirby/kirby/blob/617a07aa0151aa4b1a3735b3b5e1a41ccc244a43/src/Api/Api.php#L671) with the following for testing?

```php
$errorMessage = $upload['error'];
```

The result will be the [constant value of the upload error](http://www.php.net/manual/en/features.file-upload.errors.php). In case you can't figure out the reason yourself, please open a separate issue. Thanks!

**Comment by mrflix** [comment]
I just ran into this error in a server environment when uploading a user avatar. Because of the error the avatar didn't get applied (maybe because the profile.jpg.txt doesn't get created) and trying again didn't work because profile.jpg then already exists.

@rasteiner thanks for providing a temporary fix.

**Comment by HashandSalt** [comment]
I am also running into this, and also have my local sites on their own volume rather then the same drive MacOs is on.

Also seeing file hooks not firing (im setting tempate in the file meta according to file type)

```
'file.create:after' => function (Kirby\Cms\File $file) {

  if ($file->parent()->template() == 'client') {

    if ($file->type() == 'video') {                
        $file->update([
            'template'    => 'video'
        ]);

    } elseif ($file->type() == 'image') {

        if (!$file->template() == 'poster') {  
            $file->update([
                'template'    => 'shot'
            ]);
        } 

    }
}
}
```

**Comment by afbora** [comment]
> Also seeing file hooks not firing (im setting tempate in the file meta according to file type)

@HashandSalt Which Kirby version do you use?

**Comment by HashandSalt** [comment]
@afbora seen the issue in Kirby 3.9.1 and Kirby 3.9.2 and also using PHP 8.1 and PHP 8.2

Here is the message i saw

![image](https://user-images.githubusercontent.com/28439755/223716791-235e8fc0-4fe3-4af0-962d-9921f5a8c7c2.png)

**Comment by afbora** [comment]
> Also seeing file hooks not firing (im setting tempate in the file meta according to file type)

I mean that in 3.9.2, `updating file template` issue should be working, not for `Operation not permitted`

**Comment by HashandSalt** [comment]
Ok so it has been partially resolved? I have applied the patch from high up in this thread so its working for me now in the meantime.

**Comment by afbora** [comment]
No, updating file template is different issue https://github.com/getkirby/kirby/issues/5049 and fixed in 3.9.2. `Operation not permitted` issue still not fixed yet.

**Comment by iskrisis** [comment]
It's wierd for me it also happens on sites that are on non-internal volume. It's slow spinning disk with lots of space. I've tested it and it doesn't happen on main NVMe drive.

Is it possible that this just has something to do with speed of disk / race conditions?

**Comment by rasteiner** [comment]
> It's wierd for me it also happens on sites that are on non-internal volume. It's slow spinning disk with lots of space. I've tested it and it doesn't happen on main NVMe drive.
> 
> Is it possible that this just has something to do with speed of disk / race conditions?

If I read that correctly, it's always the same problem: "You can't move (without errors) between filesystems".
Your `/tmp` folder is probably on your "main" NVMe drive, having also the `content` folder there solves the issue, but as soon as you have the `content` on another drive (or another partition) PHP has to move to another filesystem and that causes the error message.

**Comment by iskrisis** [comment]
That makes lots of sense. And yeah it probably means it's not a bug at all. But i just have to mention i had this setup forever and it has started to happen just with the most recent versions.

**Comment by lukasbestle** [comment]
The reason why the error only started to appear recently is that we copied uploaded files from the temp dir before and now [move them](https://github.com/getkirby/kirby/pull/4943) to ensure that the temp files don't sit in the temp dir forever. However this now has the side effect that @rasteiner explained.

**Comment by lukasbestle** [comment]
Idea from a discussion with Nico:

If I understood it correctly, the move operation does succeed even if there is a warning. So this means that we really only need to silence this particular warning. We could do it like this:

- Use `Helpers::handleErrors()` to catch the warning from the `rename()` function.
- Check if the warning is "Operation not permitted". If yes, validate that the target file exists. If that's the case, drop the warning and return `true`.
- If the warning is different or the move wasn't successful, pass on the warning and return `false`.

Then we wouldn't need another method. @rasteiner What do you think?

**Comment by iskrisis** [comment]
Tbh i am not sure it's even worth caring about. There is only one server environment where i think it could be issue and that's block storage cloud providers offer. I am not sure how it will behave there but it works as mounted external drive so it's probably similar to my desktop setup.

**Comment by lukasbestle** [comment]
Given that there are now several people who have this issue on different server setups, we think it's worth fixing.

**Comment by rasteiner** [comment]
> * Use `Helpers::handleErrors()` to catch the warning from the `rename()` function.
> * Check if the warning is "Operation not permitted". If yes, validate that the target file exists. If that's the case, drop the warning and return `true`.
> * If the warning is different or the move wasn't successful, pass on the warning and return `false`.
> 
> Then we wouldn't need another method. @rasteiner What do you think?

Sure, that's essentially the elaborate version of what I proposed [above](https://github.com/getkirby/kirby/issues/5024#issuecomment-1408367343). What held me back was the breaking change of throwing an exception, it didn't actually occur to me that you could just re-emit the 90s style warning via `trigger_error` 😅

Maybe it'd be worth adding a `//@TODO` comment that reminds you to replace `trigger_error` with a `throw` in the next major version. 

But yes, I'd prefer having the toolkit intelligently handle the errors rather than having to think about "atomic or not move" :)

**Comment by bvdputte** [comment]
FWIW I also started to encounter this issue 😭

**Comment by lukasbestle** [comment]
> it didn't actually occur to me that you could just re-emit the 90s style warning via `trigger_error` 😅

We don't even have to use `trigger_error()`. If the error handler returns `false`, the normal PHP error handler continues, so the original warning is passed on. So I don't think we even need to switch to an exception here.

**Comment by rasteiner** [comment]
> If the error handler returns false, the normal PHP error handler continues

😮 TIL...

**Comment by matobeag** [comment]
I'm experiencing the same problem, and in addition to that, the uploaded files don't have the correct file template.

**Comment by lukasbestle** [comment]
@rasteiner @mrflix @HashandSalt @bvdputte @manuelvonrotz I've implemented the solution we discussed in this pull request: https://github.com/getkirby/kirby/pull/5124

Could you please try it in your setups to check if it fixes the issue for you? Then we'll be able to already include it in 3.9.3 next week.

**Comment by bvdputte** [comment]
@lukasbestle , I've just checked this patch on 3.9.3-rc1, and it does not solve the issue for me?

The file is uploaded correctly and its template file is created correctly. But I still get that error warning in the panel and the files field does not pickup the just uploaded file.

Edit: 
FWIW; Both patches proposed by @rasteiner in https://github.com/getkirby/kirby/issues/5024#issuecomment-1403934952 do seem to fix the problem.

**Comment by rasteiner** [comment]
tested with
```bash
composer require getkirby/cms:dev-fix/5024-move-tmp -W
```
can confirm that problem persists. I'll do some tests.

Edit: it seems to work when we remove the "is $oldRoot deleted" check. I don't know yet if that is because the old root actually doesn't get deleted or because of stat cache... 
Edit2: only clearing the stat cache doesn't seem to help, but I still left it in there because [in theory `file_exists` is cached](https://www.php.net/manual/en/function.clearstatcache.php). However, unlinking $oldRoot, should it still exist, seems to work:

```php
                // actually move the file
                return Helpers::handleErrors(
                        fn (): bool => rename($oldRoot, $newRoot),
 
                        // if the rename was non-atomic because of a different
                        // filesystem (e.g. from `/tmp`) but still succeeded,
                        // @codeCoverageIgnoreStart
                        fn (int $errno, string $errstr): bool => (
                                Str::endsWith($errstr, 'Operation not permitted') &&
                                clearstatcache() === null &&
                                file_exists($newRoot) === true &&
                                (file_exists($oldRoot) === false || @unlink($oldRoot))
                        ),
                        // @codeCoverageIgnoreEnd

                        // consider it a success (dropping the superfluous warning)
                        true
                );

**Comment by lukasbestle** [comment]
Thanks for investigating. Maybe that's actually the culprit of the warning: PHP can move the file by copying it to the different file system but fails at unlinking the original file.

To be honest that worries me. How can we ensure that the file is *correctly* and *completely* moved in this case? By running `unlink()` ourselves, we potentially delete the only complete version of the file.

**Comment by lukasbestle** [comment]
Considering that, I feel like we should scrap that solution and go with an explicit "copy and delete" for uploaded files.

Pinging @distantnative for opinions.

**Comment by rasteiner** [comment]
another approach could be to choose the strategy based on whether or not the source and target are on the same device:

```php 
if(stat($oldRoot)['dev'] === stat(dirname($newRoot))['dev']) {
  // move by rename
} else {
  // move by copy
}
```

I've just tested and in fact `/tmp` and the content folder on the affected server are on "different device ids", while locally (where rename works) they are on the same.

**Comment by lukasbestle** [comment]
I think that's a great solution! Because of the PHP stat cache, the performance impact should be pretty low. I'll implement that for 3.9.4 unless there are other ideas.
