### ISSUE TITLE
[v4] Infinite reload with Custom Block Selector Plugin installed

### ISSUE THREAD

**Issue by tobimori** [k-next/kirby#5263]
## Description
With the [Kirby Visual Block Selector Plugin](https://github.com/junohamburg/kirby-visual-block-selector) installed, the panel reloads indefinitely.

## To reproduce
Install Kirby 4 Beta & the linked plugin above.

## Your setup
**Kirby Version**  v4.0.0-alpha.2

**Comment by distantnative** [comment]
Cannot reproduce this. Works fine for me with alpha.2:
<img width="1314" alt="Screenshot 2023-06-10 at 11 31 27" src="https://github.com/getkirby/kirby/assets/3788865/a5c7d6b7-8e5e-4414-a535-5b1be4637ce2">

**Comment by medienbaecker** [comment]
I also use this plugin in a v4 installation without issues.

**Comment by tobimori** [comment]
hm. i'll check if I can reproduce it again.

**Comment by tobimori** [comment]
Tries to access the API route on the Login site already and fails with "401 Unauthorized", then reloads, tries again. Works when already logged in. I can't remember having this issue on Kirby 3.9.4 installations, can you check again? I assume it's related to changes in the plugin registry.

**Comment by distantnative** [comment]
Could reproduce.

I have suggested one change to the core (trying to avoid unauthenticated endless loops), but also the plugin needs to add a small change for v4 (https://github.com/junohamburg/kirby-visual-block-selector/issues/2).

**Comment by SebastianEberlein-JUNO** [comment]
We just released a new version with a fix: https://github.com/junohamburg/kirby-visual-block-selector/releases/tag/1.1.1

**Comment by distantnative** [comment]
@bastianallgeier I think this isn't fixed just because the plugin circumvents it now. We should fix this in the core too

**Comment by bastianallgeier** [comment]
@distantnative Ok, you are right. I saw your PR afterwards. Then it should be fixed now on our side as well :)
